# Generated by Django 5.1.4 on 2025-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationcode_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email преподавателя')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Кафедра')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('academic_degree', models.CharField(blank=True, max_length=100, verbose_name='Ученая степень')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Email преподавателя',
                'verbose_name_plural': 'Email преподавателей',
                'ordering': ['email'],
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ученая степень'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.IntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Факультет/Институт'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.CharField(blank=True, max_length=50, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('professor', 'Преподаватель'), ('admin', 'Администратор')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
