# Generated by Django 5.1.4 on 2025-06-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacheremail_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheremail',
            name='academic_degree',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='academic_degree',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
