# Generated by Django 5.1.4 on 2025-06-13 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название корпуса')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='buildings/', verbose_name='Изображение')),
                ('floors', models.PositiveIntegerField(default=1, verbose_name='Количество этажей')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, verbose_name='Номер аудитории')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('room_type', models.CharField(choices=[('classroom', 'Аудитория'), ('laboratory', 'Лаборатория'), ('lecture', 'Лекционная'), ('admin', 'Административная'), ('library', 'Библиотека'), ('computer', 'Компьютерный класс'), ('conference', 'Конференц-зал'), ('workshop', 'Мастерская')], default='classroom', max_length=20, verbose_name='Тип аудитории')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('equipment', models.JSONField(blank=True, default=list, verbose_name='Оборудование')),
                ('is_accessible', models.BooleanField(default=True, verbose_name='Доступна для использования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='campus.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['building', 'floor', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], verbose_name='Общая оценка')),
                ('category', models.CharField(choices=[('cleanliness', 'Чистота'), ('equipment', 'Оборудование'), ('comfort', 'Комфорт'), ('accessibility', 'Доступность'), ('lighting', 'Освещение'), ('acoustics', 'Акустика'), ('temperature', 'Температура'), ('general', 'Общее впечатление')], default='general', max_length=20, verbose_name='Категория отзыва')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('cleanliness_rating', models.IntegerField(blank=True, choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], null=True, verbose_name='Чистота')),
                ('equipment_rating', models.IntegerField(blank=True, choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], null=True, verbose_name='Оборудование')),
                ('comfort_rating', models.IntegerField(blank=True, choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], null=True, verbose_name='Комфорт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reviews', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='campus.room')),
            ],
            options={
                'verbose_name': 'Отзыв об аудитории',
                'verbose_name_plural': 'Отзывы об аудиториях',
                'ordering': ['-created_at'],
                'unique_together': {('room', 'author')},
            },
        ),
    ]
